### ISSUE TITLE
Add Mongo support

### ISSUE THREAD

**Issue by frsela** [telefonicaid/wakeup_platform#11]
libs/mobile_networks.js is using Redis now.
Add a new mobile_networks.js with Mongo support is needed :)

**Comment by frsela** [comment]
move out from shared libraries this one since is not needed by local node

**Comment by frsela** [comment]
Reduced priority. Deployment accepted Redis as a valid backend.

**Comment by willyaranda** [comment]
No mongo, no redis. Just RAM and plain JSON files
