### ISSUE TITLE
Remove Redis dependency

### ISSUE THREAD

**Issue by frsela** [telefonicaid/wakeup_platform#35]
In a meeting with deployment we decided to drop redis since we only store a configuration file.

Remove redis and create a new networks JSON file

**Comment by willyaranda** [comment]
Merged \o/

![eb87b33de9388c8c9168bd9e64eebb2327b7a229153bd14233a033df56f1e1f9](https://f.cloud.github.com/assets/679157/2104371/aaab26b2-8f7a-11e3-82dd-12a492f48c94.jpg)
