### ISSUE TITLE
New API to get supported networks (netinfo router)

### ISSUE THREAD

**Issue by frsela** [telefonicaid/wakeup_platform#37]
`GET https://<host>:<port>/netinfo`

Returns a JSON array with all suported networks:

```
{
  data: [
    {
      mcc,
      mnc,
      netid,
      range,
      status
    }
  ]
}
```

**Comment by willyaranda** [comment]
Should we store the info in the `process` object?

**Comment by willyaranda** [comment]
https://github.com/telefonicaid/wakeup_platform_global/pull/5

**Comment by frsela** [comment]
PR: https://github.com/telefonicaid/wakeup_platform_global/pull/8

Response example: [{"netid":"214-07","mccmnc":"214-07","range":"10.0.0.0/8","offline":true}]

**Comment by willyaranda** [comment]
Merged. Still pending to use it on PNS checker.
